import Head from 'next/head'
import Link from "next/link"
import styles from '../styles/Home.module.css'




export default function demographicQuestionnaire() {

    return (
        <div className={styles.dualPaneContainer}>
        <Head>
            <title>ITRE Driving Sim Helper Tool</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        </Head>
        <div className={styles.leftPaneContainerPurple}>
                <main className={styles.leftPaneMain}>
                    <h1>Pre-Trial Questionnaire</h1>
                    <Link href="/simulatorOne" >
                        <button>Proceed to &rarr;
                            <code>
                                Simulator Sickness Questions
                            </code>
                        </button>
                    </Link>
                </main>
            </div>
            <div className={styles.rightPaneContainer}>
                <main className={styles.rightPaneMain}>
                    <div className={styles.rightPaneText}>
                    <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdO1yIQ99xGs0mL5ukQx-XiW46L-b0ap7Q2QuqU7-4w5MTcFg/viewform?embedded=true" width="550" height="680" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
                    </div>
                </main>
            </div>
        </div>
    )
}
