import Head from 'next/head'

import styles from '../styles/Home.module.css'
import MediaQuery from 'react-responsive'

import LandingPage from './landing'
// import React, { useState, useEffect } from 'react';


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>ITRE Driving Sim Helper Tool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </Head>
        <MediaQuery 
          minDeviceWidth={1024} and query="(orientation: landscape)" 
          className={styles.landingPage}
        >
          <LandingPage />
        </MediaQuery>
        <MediaQuery query="(max-device-width: 1023px)">
            <h2>Your screen size is too small to use this application</h2>
        </MediaQuery>
    </div>
  )
}
