import Head from "next/head"
import Link from "next/link"
import styles from "../styles/Home.module.css"

import React from "react"


function useStickyState(defaultValue, key) {
    const [value, setValue] = React.useState(() => {
        const stickyValue = window.localStorage.getItem(key);
        return stickyValue !== null
        ? JSON.parse(stickyValue)
        : defaultValue;
    });
    React.useEffect(() => {
        window.localStorage.setItem(key, JSON.stringify(value));
    }, [key, value]);
    return [value, setValue];
}


export default function LandingPage() {

const [
    count,
    setCount
] = useStickyState(0, "count");


console.log({count})

return (
        // <div className={styles.landingContainer}>
        // <Head>
        //     <title>ITRE Driving Sim Helper Tool</title>
        //     <meta name="description" content="Generated by create next app" />
        //     <link rel="icon" href="/favicon.ico" />
        //     <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        // </Head>
        // <main className={styles.main}>
        //     <h1 className={styles.title}>
        //     Welcome, <span>Host!</span>
        //     </h1>
        //     <p className={styles.description}>
        //         Please select the option best describing your research subject to begin.
        //     </p>
        // </main>
        // <footer className={styles.footer}>
        //     <p>Institute for Transportaion Research and Education</p> &nbsp;
        //     <img src="/images/itre-arrow.png" />
        //     <p>Division of Highway Systems</p>
        // </footer>
        // </div>

        <div className={styles.dualPaneContainer}>
            <Head>
                <title>Driver Simulation Host Tool</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.leftPaneContainer}>
                <main className={styles.leftPaneMain}>
                    <h1>Welcome, Host!</h1>
                    <p>This tool is designed to ensure that you accurately present all the necessary materials and information to your research subject effortlessly and consistently.</p>
                </main>
            </div>
            <div className={styles.rightPaneContainer}>
                <div className={styles.rightPaneTop}>
                    Subject: 
                </div>
                <main className={styles.rightPaneMain}>
                    <div className={styles.rightPaneText}>
                        <div className={styles.checklist}>
                            <div className={styles.participantInfo}>
                                <h2>Participant Information</h2>
                                <label>
                                    Name: &nbsp;
                                    <input type="text" name="name" />
                                </label>
                                <label>
                                    Subject Number: &nbsp;
                                    <input type="text" name="name" />
                                </label>
                                <div className={styles.box}>
                                    <label>
                                        Present: &nbsp;
                                        <input type="radio" name="present" />
                                    </label>
                                    <label>
                                        Absent: &nbsp;
                                        <input type="radio" name="absent" />
                                    </label>
                                </div>
                                <div className={styles.box}>
                                    <label>
                                        Present: &nbsp;
                                        <input type="radio" name="present" />
                                    </label>
                                    <label>
                                        Absent: &nbsp;
                                        <input type="radio" name="absent" />
                                    </label>
                                </div>
                            </div>
                        <h2>Checklist</h2>
                        <label>
                            <input type="radio" name="name" />
                            &nbsp; Informed Consent Form
                        </label>
                        <label>
                            <input type="radio" name="name" />
                            &nbsp; Informed Consent Addendum (Covid-19)
                        </label>
                        </div>
                    </div>
                    
                </main>
                <div className={styles.rightPaneBottom}>
                    <Link href="/demographic" >
                        <button>Proceed to &rarr; <code>Demographic Questionnaire</code></button>
                    </Link>
                </div>
            </div>
        </div>
    )
}



