import Head from 'next/head'
import Link from "next/link"
import styles from '../styles/Home.module.css'




export default function simulatorSicknessQuetionsOne() {

    return (
        <div className={styles.dualPaneContainer}>
        <Head>
            <title>ITRE Driving Sim Helper Tool</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        </Head>
        <div className={styles.leftPaneContainerGreen}>
                <main className={styles.leftPaneMain}>
                    <h1>Simulator Sickness Questionnaire Version One</h1>
                    <Link href="/trainingSim">
                        <button>Proceed to &rarr;
                            <code>
                                Training Simulation
                            </code>
                        </button>
                    </Link>
                </main>
            </div>
            <div className={styles.rightPaneContainer}>
                <main className={styles.rightPaneMain}>
                    <iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSIwXUPQrF-bPeK4lrVm32_8colujey2f1aeZ942X7-EMaLbEvhUjYZalqRTFkc-jHkeLhdoFsv2Noi/pubhtml?widget=true&amp;headers=false" width="620" height="680" frameborder="0" marginheight="0" marginwidth="0"></iframe>
                </main>
            </div>
        </div>
    )
}
