import Head from 'next/head'
import Link from "next/link"
import styles from '../styles/Home.module.css'




export default function simulatorSicknessQuetionsOne() {

    return (
        <div className={styles.dualPaneContainer}>
        <Head>
            <title>ITRE Driving Sim Helper Tool</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        </Head>
        <div className={styles.leftPaneContainer}>
                <main className={styles.leftPaneMain}>
                    <h1>Training Sim</h1>
                    <Link href="/demandRanking">
                        <button>Proceed to &rarr;
                            <code>
                                Demand Ranking
                            </code>
                        </button>
                    </Link>
                </main>
            </div>
            <div className={styles.rightPaneContainer}>
                <main className={styles.rightPaneMain}>
                    <iframe src="https://ufl.qualtrics.com/jfe/form/SV_blbTNlywtcmtNxc" width="620" height="680" frameborder="0" marginheight="0" marginwidth="0"></iframe>
                </main>
                <div className={styles.rightPaneBottom}>
                    <Link href="https://ufl.qualtrics.com/jfe/form/SV_blbTNlywtcmtNxc" >
                        <button><code>View on Qualtrics</code></button>
                    </Link>
                </div>
            </div>
        </div>
    )
}
